#!/bin/bash

set -e

echo "=== Building Metamorph Shellcode ==="

# Usar metamorph.c (versión final sin debug)
SOURCE_FILE="src/metamorph/metamorph.c"

echo "Using source: $SOURCE_FILE"

# Compilar metamorph.c como objeto position-independent
# -Os optimiza para tamaño
gcc -fPIC -fno-stack-protector -nostdlib \
    -fno-asynchronous-unwind-tables \
    -fno-merge-constants \
    -Os \
    -c $SOURCE_FILE -o obj/metamorph.o

# Extraer solo la sección .metamorph
objcopy -O binary --only-section=.metamorph \
    obj/metamorph.o obj/metamorph_raw.bin

# Quitar el ud2 (0f 0b) si está al final
# Buscar y remover los últimos 2 bytes si son 0f 0b
python3 -c "
import sys
data = open('obj/metamorph_raw.bin', 'rb').read()
# Si termina en ud2 (0f 0b), quitarlo
if len(data) >= 2 and data[-2:] == bytes([0x0f, 0x0b]):
    data = data[:-2]
    print('Removed trailing ud2', file=sys.stderr)
open('obj/metamorph.bin', 'wb').write(data)
"

# Obtener tamaño
SIZE=$(wc -c < obj/metamorph.bin)
echo "Shellcode size: $SIZE bytes"

# Obtener offset de metamorph_mutate_self dentro de la sección .metamorph
ENTRY_OFFSET=$(objdump -t obj/metamorph.o | grep "metamorph_mutate_self" | awk '{print "0x"$1}')
ENTRY_OFFSET_DEC=$((ENTRY_OFFSET))
echo "Entry offset (metamorph_mutate_self): $ENTRY_OFFSET ($ENTRY_OFFSET_DEC decimal)"

# Convertir a array de C
echo "/* Auto-generated by build_shellcode.sh */" > include/metamorph_shellcode.h
echo "#ifndef METAMORPH_SHELLCODE_H" >> include/metamorph_shellcode.h
echo "#define METAMORPH_SHELLCODE_H" >> include/metamorph_shellcode.h
echo "" >> include/metamorph_shellcode.h
echo "#define METAMORPH_SHELLCODE_SIZE $SIZE" >> include/metamorph_shellcode.h
echo "#define METAMORPH_ENTRY_OFFSET $ENTRY_OFFSET_DEC" >> include/metamorph_shellcode.h
echo "" >> include/metamorph_shellcode.h
echo "unsigned char metamorph_shellcode[] = {" >> include/metamorph_shellcode.h

# Convertir bytes a hex
xxd -i < obj/metamorph.bin | grep -v "unsigned" | grep -v "};" >> include/metamorph_shellcode.h

echo "};" >> include/metamorph_shellcode.h
echo "" >> include/metamorph_shellcode.h
echo "#endif" >> include/metamorph_shellcode.h

echo "✅ Shellcode generated: include/metamorph_shellcode.h"